In [3]:
import os
import glob
import math 
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt

In [4]:
pathfile = "D:/01_Git/DADS5001-Midterm/01_Data/"
from glob import glob
pathData = [y for x in os.walk(pathfile) for y in glob(os.path.join(x[0], "*.csv"))]

df = pd.DataFrame()
for i in pathData:
    temp = pd.read_csv(i)
    df = df.append(temp)
    

print(df.head())
print(df.shape)

C:\Users\Anyamanee\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

      No. announce_date Notified date   sex   age Unit nationality  \
0  816990     12/8/2021     11/8/2021   ชาย   7.0   ปี    Thailand
1  816991     12/8/2021     11/8/2021   ชาย   1.0   ปี    Thailand
2  816992     12/8/2021     11/8/2021   ชาย  35.0   ปี    Thailand
3  816993     12/8/2021     11/8/2021  หญิง  33.0   ปี    Thailand
4  816994     12/8/2021     11/8/2021  หญิง  14.0   ปี    Thailand

  province_of_isolation                                         risk  \
0              เชียงราย                                        อื่นๆ
1              เชียงราย                                        อื่นๆ
2              เชียงราย                                        อื่นๆ
3              เชียงราย                                        อื่นๆ
4              เชียงราย  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

  province_of_onset district_of_onset  Unnamed: 11
0               NaN               NaN          NaN
1               NaN               NaN          NaN
2               NaN               NaN          NaN
3               NaN               NaN          NaN
4               NaN               NaN          NaN
(2459109, 12)

In [3]:
df.to_csv("mergeData_120864_280265.csv", encoding="utf_8_sig")

In [5]:
sex_unique = [x for x in set(df["sex"])]
for i in range(0,len(sex_unique)):
    #print(sex_unique[i])
    data_temp =str(sex_unique[i])
    if (data_temp.startswith("ห") == True) or (data_temp.startswith("ญ") == True) or (data_temp.endswith("ง") == True):
        df['sex'] = df['sex'].replace(sex_unique[i],'หญิง')
    elif data_temp.startswith("ช") or data_temp.startswith("น"):
        df['sex'] = df['sex'].replace(sex_unique[i],'ชาย')
    else:
        df['sex'] = df['sex'].replace(sex_unique[i],np.nan)

nan
นาย
หญง
ชาย
ร.ต.ท.
ญ
หญิิง
ช
หห
 หญิง
หญิง
หณิง

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset,Unnamed: 11
0,816990,12/8/2021,11/8/2021,ชาย,7.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN,NaN
1,816991,12/8/2021,11/8/2021,ชาย,1.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN,NaN
2,816992,12/8/2021,11/8/2021,ชาย,35.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN,NaN
3,816993,12/8/2021,11/8/2021,หญิง,33.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN,NaN
4,816994,12/8/2021,11/8/2021,หญิง,14.0,ปี,Thailand,เชียงราย,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,NaN,NaN,NaN

In [ ]:
df.to_csv("mergeData_120864_280265_SexClean.csv", encoding="utf_8_sig")
df.head()

In [7]:
df["announce_date"] =  pd.to_datetime(df["announce_date"], dayfirst = True)
df["Notified date"] =  pd.to_datetime(df["Notified date"], dayfirst = True)
df.loc[:,["announce_date","Notified date"]].describe()

<ipython-input-7-69b6633e262a>:3: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.loc[:,["announce_date","Notified date"]].describe()
<ipython-input-7-69b6633e262a>:3: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.loc[:,["announce_date","Notified date"]].describe()

              announce_date        Notified date
count               2459109              2459109
unique                  218                  218
top     2022-02-26 00:00:00  2022-02-25 00:00:00
freq                  25615                25615
first   2021-08-12 00:00:00  2021-08-11 00:00:00
last    2022-03-17 00:00:00  2022-03-16 00:00:00

In [8]:
df['diff_Date'] = (df['announce_date'] - df['Notified date']).dt.days

print(df['diff_Date'].describe(),'\n',df.shape)
df= df.loc[df['diff_Date']>=0]

df.to_csv("mergeData_120864_280265_date.csv", encoding="utf_8_sig")
df.shape

count    2.459109e+06
mean     1.000002e+00
std      2.209030e-03
min     -1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      2.000000e+00
Name: diff_Date, dtype: float64
 (2459109, 13)

(2459108, 13)

In [9]:
data =df
data = data.reset_index(drop =True)

In [10]:
data.shape

(2459108, 13)

In [11]:
set(data["Unit"])

{nan, 'ปี', 'วัน', 'เดือน'}

In [14]:
data['age'] = data['age'].replace("35/11",np.nan)

In [15]:
data['age'] = data['age'].astype(float)

In [ ]:
data['age'] = data['age']

In [21]:
result = data.isnull().sum()
print(result)

No.                            0
announce_date                  0
Notified date                  0
sex                       123968
age                       190853
Unit                      211168
nationality               201517
province_of_isolation       3684
risk                          93
province_of_onset         297403
district_of_onset         341846
Unnamed: 11              2459108
diff_Date                      0
dtype: int64

In [22]:
df_dropped = data.dropna(subset=['Unit'])

In [23]:
df_dropped.shape

(2247940, 13)

In [111]:
result = df_dropped.isnull().sum()
print(result)

No.                            0
announce_date                  0
Notified date                  0
sex                        63220
age                         2263
Unit                           0
nationality                    0
province_of_isolation       3320
risk                          71
province_of_onset         206858
district_of_onset         238757
Unnamed: 11              2247940
diff_Date                      0
dtype: int64

In [26]:
df_dropped['age'] = df_dropped['age'].fillna(np.nan)

<ipython-input-26-ff7c9da28351>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped['age'] = df_dropped['age'].fillna(np.nan)

In [33]:
df_dropped["nationality"] = df_dropped["nationality"].str.lower()
set(df_dropped["nationality"])

<ipython-input-33-050d7c0c5e83>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped["nationality"] = df_dropped["nationality"].str.lower()

{'afghan',
 'afghan / afghani',
 'african',
 'albanian',
 'algerian',
 'american',
 'american samoa',
 'arabi',
 'argentine / argentinian',
 'armenian',
 'au',
 'australian',
 'austria',
 'austrian',
 'azerbaijan',
 'bahraini',
 'bangladeshi',
 'belarusian',
 'belgian',
 'bhutan',
 'bosnian',
 'bosnian/herzegovinian',
 'brazilian',
 'british',
 'british / english',
 'british / northern irish',
 'british / scottish',
 'british / welsh',
 'british/english',
 'bruneian',
 'bulgarian',
 'burmese',
 'cambodia',
 'cambodian',
 'cameroon',
 'canadian',
 'chilean',
 'china',
 'chinese',
 'colombian',
 'croatian',
 'cuban',
 'cypriot',
 'czech',
 'danish',
 'dutch',
 'ecuadorian',
 'egyptian',
 'emirate',
 'emirati',
 'eritrean',
 'estonian',
 'ethiopian',
 'fijian',
 'filipino',
 'finnish',
 'france',
 'french',
 'gambian',
 'georgian',
 'german',
 'germen',
 'ghanaian',
 'greek',
 'gremany',
 'guinean',
 'hungarian',
 'icelandic',
 'indian',
 'indonesian',
 'iranian',
 'iraqi',
 'irish',
 'israeli',
 'italian',
 'ivorian',
 'japanese',
 'jordanian',
 'kazakh / kazakhstani',
 'kenyan',
 'korean',
 'kosovan',
 'kuwaiti',
 'kyrgyz',
 'laos',
 'laotian / lao',
 'laotian/lao',
 'latvian',
 'lebanese',
 'liberian',
 'libyan',
 'lithuanian',
 'luxembourgish',
 'malaysian',
 'maldivian',
 'malian',
 'maltese',
 'mauritians',
 'mexican',
 'mongolian',
 'moroccan',
 'myanmar',
 'namibian',
 nan,
 'nepalese / nepali',
 'new zealand',
 'nigerian',
 'north korean',
 'norwegian',
 'omani',
 'other',
 'pakistani',
 'palestinian',
 'peruvian',
 'philippines',
 'phutan',
 'polish',
 'portuguese',
 'qatari',
 'romanian',
 'russian',
 'saudi arabian',
 'serbian',
 'singaporean',
 'slovak / slovakian',
 'slovenian / slovene',
 'somali / somalian',
 'south african',
 'south korea',
 'south korean',
 'spanish',
 'sri lankan',
 'sudanese',
 'swaziland',
 'swedish',
 'swiss',
 'syrian',
 'taiwanese',
 'tajik',
 'thai',
 'thailand',
 'trinidad and tobago',
 'tunisian',
 'turkcish',
 'turkish',
 'uae',
 'ugandan',
 'ukrainian',
 'united arab emirates',
 'united kingdom',
 'uruguayan',
 'uzbek',
 'uzbekistan',
 'venezuelan',
 'vietnamese',
 'yemeni / yemenite',
 'zambian',
 'zimbabwean',
 '\xa0bulgarian',
 'สวีเดน',
 'ไม่ระบุ'}

In [36]:
nationality_unique = [x for x in set(df_dropped["nationality"] )]
for i in range(0,len(nationality_unique)):
    print(nationality_unique[i])
    data_input =input("replace word: ")
    if data_input != "":
        df_dropped['nationality'] = df_dropped['nationality'].replace(nationality_unique[i],data_input)

syrian
replace word:
สวีเดน
replace word: Swedish

<ipython-input-36-000167383219>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped['nationality'] = df_dropped['nationality'].replace(nationality_unique[i],data_input)

mexican
replace word: Mexican
uruguayan
replace word:
bruneian
replace word:
maldivian
replace word:
emirate
replace word: Emirati
united kingdom
replace word: British
afghan
replace word:
palestinian
replace word:
myanmar
replace word: Burmese
lithuanian
replace word:
sri lankan
replace word:
emirati
replace word:
nigerian
replace word:
trinidad and tobago
replace word:
pakistani
replace word:
fijian
replace word:
gremany
replace word: German
mongolian
replace word:
laotian/lao
replace word: Laotian
tunisian
replace word:
namibian
replace word:
taiwanese
replace word:
danish
replace word:
argentine / argentinian
replace word: Argentinian
ethiopian
replace word:
bulgarian
replace word:
kuwaiti
replace word:
azerbaijan
replace word: Azerbaijani
romanian
replace word:
albanian
replace word:
finnish
replace word:
brazilian
replace word:
libyan
replace word:
british / scottish
replace word:
north korean
replace word:
african
replace word:
italian
replace word:
somali / somalian
replace word: Somalian
chilean
replace word:
cuban
replace word:
filipino
replace word: Philippine
venezuelan
replace word:
other
replace word: other
malaysian
replace word:
hungarian
replace word: hungarian
ivorian
replace word:
yemeni / yemenite
replace word: yemeni
indian
replace word:
korean
replace word:
liberian
replace word:
german
replace word:
british
replace word:
american
replace word: US
uae
replace word: Emirati
phutan
replace word: Bhutanese
malian
replace word:
armenian
replace word:
ไม่ระบุ
replace word: nan
bhutan
replace word: Bhutanese
moroccan
replace word:
british/english
replace word: british
zambian
replace word:
kyrgyz
replace word:
lebanese
replace word:
peruvian
replace word:
polish
replace word:
iranian
replace word:
bosnian/herzegovinian
replace word: bosnian
bahraini
replace word:
cameroon
replace word: Cameroonian
tajik
replace word:
icelandic
replace word:
germen
replace word: german
eritrean
replace word:
croatian
replace word:
kosovan
replace word:
austria
replace word: Austrian
canadian
replace word:
nepalese / nepali
replace word: nepalese
norwegian
replace word:
portuguese
replace word:
swaziland
replace word: Swazi
cambodia
replace word: Cambodian
united arab emirates
replace word: Emirati
slovak / slovakian
replace word: Slovak
dutch
replace word:
american samoa
replace word:
serbian
replace word:
austrian
replace word:
laotian / lao
replace word: laotian
maltese
replace word:
colombian
replace word:
ghanaian
replace word:
georgian
replace word:
new zealand
replace word:
french
replace word:
irish
replace word:
cambodian
replace word:
burmese
replace word:
sudanese
replace word:
latvian
replace word:
british / welsh
replace word:
russian
replace word:
thai
replace word:
uzbek
replace word:
au
replace word: nan
swiss
replace word:
singaporean
replace word:
chinese
replace word:
south korea
replace word: Korean
japanese
replace word: japanese
australian
replace word:
jordanian
replace word:
guinean
replace word:
ecuadorian
replace word:
afghan / afghani
replace word: Afghan
ukrainian
replace word:
 bulgarian
replace word: bulgarian
saudi arabian
replace word: saudi
turkcish
replace word: Turkish
omani
replace word:
south african
replace word:
south korean
replace word: Korean
zimbabwean
replace word:
china
replace word: Chinese
laos
replace word: Laotian
mauritians
replace word: mauritian
belgian
replace word:
cypriot
replace word:
iraqi
replace word:
czech
replace word:
british / northern irish
replace word:
arabi
replace word: Arabian
greek
replace word:
belarusian
replace word:
gambian
replace word:
vietnamese
replace word:
luxembourgish
replace word:
kazakh / kazakhstani
replace word: Kazakh
thailand
replace word: Thai
bangladeshi
replace word: Bangladeshi
algerian
replace word:
british / english
replace word: british
egyptian
replace word:
estonian
replace word:
spanish
replace word:
france
replace word: French
swedish
replace word:
qatari
replace word:
indonesian
replace word:
kenyan
replace word:
ืnp.nan
replace word: nan
slovenian / slovene
replace word: slovenian
uzbekistan
replace word: Uzbek
philippines
replace word: philippine
turkish
replace word:
ugandan
replace word:
bosnian
replace word:
israeli
replace word:

In [38]:
df_dropped["nationality"] = df_dropped["nationality"].str.lower()

<ipython-input-38-9bd81c31a934>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dropped["nationality"] = df_dropped["nationality"].str.lower()

In [39]:
set(df_dropped["nationality"])

{'afghan',
 'african',
 'albanian',
 'algerian',
 'american samoa',
 'arabian',
 'argentinian',
 'armenian',
 'australian',
 'austrian',
 'azerbaijani',
 'bahraini',
 'bangladeshi',
 'belarusian',
 'belgian',
 'bhutanese',
 'bosnian',
 'brazilian',
 'british',
 'british / northern irish',
 'british / scottish',
 'british / welsh',
 'bruneian',
 'bulgarian',
 'burmese',
 'cambodian',
 'cameroonian',
 'canadian',
 'chilean',
 'chinese',
 'colombian',
 'croatian',
 'cuban',
 'cypriot',
 'czech',
 'danish',
 'dutch',
 'ecuadorian',
 'egyptian',
 'emirati',
 'eritrean',
 'estonian',
 'ethiopian',
 'fijian',
 'finnish',
 'french',
 'gambian',
 'georgian',
 'german',
 'ghanaian',
 'greek',
 'guinean',
 'hungarian',
 'icelandic',
 'indian',
 'indonesian',
 'iranian',
 'iraqi',
 'irish',
 'israeli',
 'italian',
 'ivorian',
 'japanese',
 'jordanian',
 'kazakh',
 'kenyan',
 'korean',
 'kosovan',
 'kuwaiti',
 'kyrgyz',
 'laotian',
 'latvian',
 'lebanese',
 'liberian',
 'libyan',
 'lithuanian',
 'luxembourgish',
 'malaysian',
 'maldivian',
 'malian',
 'maltese',
 'mauritian',
 'mexican',
 'mongolian',
 'moroccan',
 'namibian',
 'nan',
 'nepalese',
 'new zealand',
 'nigerian',
 'north korean',
 'norwegian',
 'omani',
 'other',
 'pakistani',
 'palestinian',
 'peruvian',
 'philippine',
 'polish',
 'portuguese',
 'qatari',
 'romanian',
 'russian',
 'saudi',
 'serbian',
 'singaporean',
 'slovak',
 'slovenian',
 'somalian',
 'south african',
 'spanish',
 'sri lankan',
 'sudanese',
 'swazi',
 'swedish',
 'swiss',
 'syrian',
 'taiwanese',
 'tajik',
 'thai',
 'trinidad and tobago',
 'tunisian',
 'turkish',
 'ugandan',
 'ukrainian',
 'uruguayan',
 'us',
 'uzbek',
 'venezuelan',
 'vietnamese',
 'yemeni',
 'zambian',
 'zimbabwean'}

In [40]:
df_dropped.to_csv("mergeData_120864_280265_nation.csv", encoding="utf_8_sig")
df_dropped.shape

(2247940, 13)

In [107]:
set(df_dropped["risk"])

{'10.อื่นๆ',
 '2.สัมผัสผู้ติดเชื้อ',
 '8.สำรวจกลุ่มเสี่ยง (survey)',
 '9.ขอตรวจหาเชื้อเอง',
 'BKK Sandbox',
 'Chonburi Sandbox',
 'Krabi Sandbox',
 'Narathiwat Sandbox',
 'Phang Nga Sandbox',
 'Phare Sandbox',
 'Phuket Sandbox',
 'Prachuap Sandbox',
 'Rayong Sandbox',
 'Samui Plus',
 'Samut Prakan Sandbox',
 'Sandbox',
 'Songkhla Sandbox',
 'State Quarantine',
 'Surin Sandbox',
 'Test and Go',
 'Trat Sandbox',
 nan,
 'การค้นหาผู้ป่วยเชิงรุกและค้นหาผู้ติดเชื้อในชุมชน',
 'คนต่างชาติเดินทางมาจากต่างประเทศ',
 'คนไทยเดินทางกลับจากต่างประเทศ',
 'ตรวจก่อนทำหัตถการ',
 'ติดเชื้อในพื้นที่',
 'ทัณฑสถาน/เรือนจำ',
 'นักกีฬา',
 'บุคลากรด้านการแพทย์และสาธารณสุข',
 'ปอดอักเสบ(Pneumonia)',
 'ผู้ที่เดินทางมาจากต่างประเทศ และเข้า AQ',
 'ผู้ที่เดินทางมาจากต่างประเทศ และเข้า HQ/AHQ',
 'ผู้ที่เดินทางมาจากต่างประเทศ และเข้า OQ',
 'พิธีกรรมทางศาสนา',
 'ระบุไม่ได้',
 'สถานที่ทำงาน',
 'สถานประกอบการ',
 'สถานศึกษา',
 'สนามมวย',
 'สัมผัสผู้ป่วยยืนยัน ภายในครอบครัว/ชุมชน/เพื่อน',
 'สัมผัสผู้ป่วยยืนยันภายในชุมชน',
 'สัมผัสผู้เดินทางจากต่างประเทศ',
 'อยู่ระหว่างสอบสวนโรค',
 'เดินทางมาจากพื้นที่เสี่ยงที่มีการระบาดของโรค',
 'ไปสถานที่ชุมชน',
 'ไปสถานที่แออัด เช่น งานแฟร์ คอนเสิร์ต'}

In [110]:
risk_unique = [x for x in set(df_dropped["risk"])]
for i in risk_unique:
    i = str(i)
    if (i.startswith("ศูนย์กักกัน ผู้ต้องกัก") == True) or (i.startswith("k") == True):
        df_dropped['risk'] = df_dropped['risk'].replace(i,'State Quarantine')

In [109]:
df_dropped.to_csv("mergeData_120864_280265_risk.csv", encoding="utf_8_sig")
df_dropped.shape

(2247940, 13)